### ISSUE TITLE
期待未来的版本中，能够直接使用vue，移除sprite-vue中的vue

### ISSUE THREAD

**Issue by laden666666** [spritejs/sprite-vue#2]
sprite-vue正是我期待的库，里面提供的功能非常让人满意。可是sprite-vue不是基于vue，而是将一个修改后的vue内置到了sprite-vue中，这样会让人担心使用sprite-vue提供的vue会导致其他模块产生一些问题。

期待以后能提供一个能够直接使用vue的版本，移除sprite-vue中的vue

**Comment by AngusFu** [comment]
听尤雨溪的分享貌似 Vue v3 应该会开放 `nodeOps`。而目前 Vue 2.x 中这个一直没对外暴露。到时候基本应该就可以解决问题。
剩下一些需要特殊处理的指令之类的，还有待观察（其实是我没细看月影这部分的实现）。

**Comment by laden666666** [comment]
如果是这样的和vue集成，其实等于没有集成。这个库虽然很强大，但是无法在项目中使用
