### ISSUE TITLE
vue.spritejs.org 网站打开就未响应啦

### ISSUE THREAD

**Issue by aolsx** [spritejs/sprite-vue#4]
非常感谢您的分享！！
官方 vue.spritejs.org 打开就未响应了，可能是某个示例的问题，您看下呗。

**Comment by akira-cn** [comment]
感觉codepen服务出了点问题，我检查了所有的demo，未发现不能运行的

回头我搬迁到demosify上吧

**Comment by akira-cn** [comment]
的确有个case跑起来有问题了，我把bug修了，感谢反馈~
